import type { NextPage } from 'next'
import Head from 'next/head'
import Countdown from 'react-countdown';

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>berlin-down</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Berlin Countdown
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2><Countdown date={new Date('Jun 13 2022')} /></h2>
            

          </div>

        </div>
      </main>

      <footer className={styles.footer}>
       
          Powered by {' '}
          <strong>mad mushrooms</strong>
      
      </footer>
    </div>
  )
}

export default Home
